#!/bin/sh

# Check if certificates exist
if [ ! -f ./localhost+2.pem ]; then
    echo "No SSL certificate found, generating one..."
    # Generate a new key and echo in an empty passphrase
    printf 'US\nMissouri\nSt. Louis\nCSE260M\nNone\nNone\ntest@localhost.com\n\n' | openssl req -x509 -newkey rsa:2048 -keyout localhost+2-key.pem -out localhost+2.pem -days 365 -passin pass:"" -passout pass:""
    # mkcert -install
    # mkcert -cert-file localhost+2.pem -key-file localhost+2-key.pem localhost 127.0.0.1 ::1
fi
exec node server.js
